version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: brainbrawler
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brainbrawler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - brainbrawler_net

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - brainbrawler_net

  backend:
    image: node:20-slim
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - /home/bb/brainbrawler/web-repository/backend:/app
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y openssl && npm install && npm run db:generate && npm run dev"
    environment:
      - DATABASE_URL=postgresql://brainbrawler:password@db:5432/brainbrawler
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-too
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - NODE_ENV=development
    networks:
      - brainbrawler_net

  frontend:
    image: node:20-slim
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - /home/bb/brainbrawler/web-repository/frontend:/app
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm start"
    environment:
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE=http://localhost:3000/api
    networks:
      - brainbrawler_net
      
  android-builder:
    image: reactnativecommunity/react-native-android
    restart: "no"
    volumes:
      - /home/bb/brainbrawler/mobile-app/BrainBrawlerMobile:/home/node/project
    working_dir: /home/node/project
    command: tail -f /dev/null
    networks:
      - brainbrawler_net

networks:
  brainbrawler_net:
    driver: bridge
    name: brainbrawler_net

volumes:
  postgres_data: 